codecov:
  notify:
    after_n_builds: 12

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
      http:
        target: 55%
        flags:
          - http
    patch:
      default:
        target: 90%
      http:
        target: 100%
        flags:
          - http

flags:
  http:
    paths:
      - discord/http.py
