codecov:
  notify:
    after_n_builds: 12

flag_management:
  individual_flags:
    - name: http
      paths:
        - discord/http.py
      carryforward: true
      statuses:
        - type: project
          target: 55%
        - type: patch
          target: 100%

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 90%
