codecov:
  notify:
    after_n_builds: 12

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        paths:
          - discord
      http:
        target: 55%
        paths:
          - tests/http
          - discord/http.py
    patch:
      default:
        target: 90%
        paths:
          - discord
      http:
        target: 100%
        paths:
          - tests/http
          - discord/http.py
